server:
  port: 7777

eureka:
  instance:
    hostname: eureka-ha1
    metadataMap.zone: zone-1
  client:
    region: Shanghai
    availabilityZones:
      Shanghai: zone-1, zone-2
    service-url:
      defaultZone: http://eureka-ha2:7778/eureka/

      # 服务注册中心的配置内容，指定服务注册中心的位置