server:
  port: 7778
spring:
  application:
    name: eureka-server
  cloud:
    inetutils:
      timeout-seconds: 10
      preferred-networks: ${SCAFFOLD_PREFERRED_NETWORKS:192.168.68.}
      prefer-ip-address: true  #访问路径可以显示IP地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/   # 服务注册中心的配置内容，指定服务注册中心的位置
