server:
  port: 7778

eureka:
  instance:
    hostname: eureka-ha2
    metadataMap.zone: zone-2
  client:
    region: Shanghai
    availabilityZones:
      Shanghai: zone-1, zone-2
    service-url:
      defaultZone: http://eureka-ha1:7777/eureka/   # 服务注册中心的配置内容，指定服务注册中心的位置
