apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 30Gi