apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
        - name: init
          image: lscr.io/linuxserver/qbittorrent:4.6.2
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: qbittorrent-config
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "WebUI\HostHeaderValidation=false" >> /config/qBittorrent/qBittorrent.conf
              echo "WebUI\Password_PBKDF2=Initial0" >> /config/qBittorrent/qBittorrent.conf
              echo "WebUI\Password=Initial0" >> /config/qBittorrent/qBittorrent.conf
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:4.6.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "100m"
            requests:
              memory: "500Mi"
              cpu: "50m"
          envFrom:
          - configMapRef:
              name: qbittorrent-config
          ports:
            - name: web-ui-port
              containerPort: 8080
            - name: tcp-port
              containerPort: 6881
              protocol: TCP
            - name: udp-port
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-data
              mountPath: /downloads
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: qbittorrent-data-pvc

