apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data-pv
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: >-
      /var/snap/microk8s/common/default-storage/media-qbittorrent-data-pv
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: media
    name: qbittorrent-data-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nickg3


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 100Mi
  hostPath:
    path: >-
      /var/snap/microk8s/common/default-storage/media-qbittorrent-config-pv
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: media
    name: qbittorrent-config-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nickg3

