apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  type: NodePort
  ports:
    - name: web-ui
      port: 8080
      targetPort: 8080
      nodePort: 30003
      protocol: TCP
    - name: tcp-connection
      port: 6881
      targetPort: 6881
      nodePort: 30004
      protocol: TCP
    - name: udp-connection
      port: 6881
      targetPort: 6881
      nodePort: 30004
      protocol: UDP
