apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
      protocol: TCP
    - port: 6881
      targetPort: 6881
      nodePort: 30004
      protocol: TCP
    - port: 6881
      targetPort: 6881
      nodePort: 30004
      protocol: UDP
